language: generic
sudo: required
services:
  - docker

before install:
  - docker build -t study/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true study/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-412805220065'
  bucket_path: 'docker-react'
  on:
    branch: 'master'
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
